# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GovTest < Formula
  desc ""
  homepage "https://github.com/dev-ujin/homebrew-gov-test"
  version "1.0.8"

  on_macos do
    on_intel do
      url "https://github.com/dev-ujin/gov-test/releases/download/v1.0.8/gov-test_Darwin_x86_64.tar.gz"
      sha256 "cf0250cce87a7069950295ec2f76ff4af686bed0198783656bc732cef97bc971"

      def install
        bin.install "gov-test"
      end
    end
    on_arm do
      url "https://github.com/dev-ujin/gov-test/releases/download/v1.0.8/gov-test_Darwin_arm64.tar.gz"
      sha256 "e8b6bb60a349c384cc8d24b1e28c16d082b425b18e946de368e7f423b3c05b60"

      def install
        bin.install "gov-test"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dev-ujin/gov-test/releases/download/v1.0.8/gov-test_Linux_x86_64.tar.gz"
        sha256 "d1eadbadf376e23097793c72a7e4f5aa63271a92d1b722535cc6b0d302d90bed"

        def install
          bin.install "gov-test"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dev-ujin/gov-test/releases/download/v1.0.8/gov-test_Linux_arm64.tar.gz"
        sha256 "39537b6dd319eef855f986c5fe190b7b6ce046edd46c7a70d7c9743b13fe28a9"

        def install
          bin.install "gov-test"
        end
      end
    end
  end
end
