# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GovTest < Formula
  desc ""
  homepage "https://github.com/dev-ujin/gov-test"
  version "1.0.7"

  on_macos do
    on_intel do
      url "https://github.com/dev-ujin/gov-test/releases/download/v1.0.7/gov-test_Darwin_x86_64.tar.gz"
      sha256 "c938f61bce01cb36da03c13e5d09c548c9f128c16955e5db40165dda2f65c6d8"

      def install
        bin.install "gov-test"
      end
    end
    on_arm do
      url "https://github.com/dev-ujin/gov-test/releases/download/v1.0.7/gov-test_Darwin_arm64.tar.gz"
      sha256 "4f6a75659aa37489e83b9d99871c9546b1de3f117be63713c80d9c8cb259fd53"

      def install
        bin.install "gov-test"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dev-ujin/gov-test/releases/download/v1.0.7/gov-test_Linux_x86_64.tar.gz"
        sha256 "e8935cf701151c474bb7b190e1a7c6094675fbb5f1e5bce6423c9daa8f23047c"

        def install
          bin.install "gov-test"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dev-ujin/gov-test/releases/download/v1.0.7/gov-test_Linux_arm64.tar.gz"
        sha256 "3efee58600572084e5764ceadcfe505100c26438b46ddbbf4c04a3eb6f48878b"

        def install
          bin.install "gov-test"
        end
      end
    end
  end
end
